<?php

/**
 * Implements hook_init
 */
function list_hal_publication_init() {
}

/**
 * Implements hook_filter_info
 */
function list_hal_publication_filter_info() {
    return array(
        'list_hal' => array(
            'title' => t('hal publications'),
            'description' => t('Active this filter to allow a user adding a special balise to build a list of publications from HAL'),
            'settings callback' => '_filter_hal_settings',
            'process callback' => '_filter_hal',
        ),
    );
}

/**
 * Implements preprocess_node
 */
function list_hal_publication_preprocess_node($variables) {
    $nodeId = $variables['nid'];
    drupal_add_css(variable_get(sprintf("node-%s.list_hal_publication.css", $nodeId)), array('type' => 'external'));
}

function _filter_hal($text, $filter) {
    $nodeId = arg(1);
    $text = html_entity_decode($text);

    if (!preg_match('/\{\{\s*type\="hal_publications"([^\}]+)\}\}/', $text, $matches)) {
        return;
    }

    if (!preg_match("#url=\"([^\"]+)\"#", strip_tags($matches[1]), $uris)) {
        return;
    }

    preg_match("/css\=\.\.\/([^&]+)&?/", $uris[1], $css);

    $cssUri = sprintf("http://hal.univ-grenoble-alpes.fr/%s", $css[1]);
    variable_set(sprintf("node-%s.list_hal_publication.css", $nodeId), $cssUri);

    $content = drupal_http_request($uris[1]);
    
    $dom = new DomDocument();
    $dom->loadHTML($content);
    
    $tags = $dom->getElementsByTagname("body");
    
    if ($tags->length != 1) {
        return;
    }

    foreach ($tags as $tag) {
        $halPublis = DOMinnerHTML($tag);
    }

    $text = str_replace($matches[0], $halPublis, $text);

    return $text;
}

function DOMinnerHTML(DOMNode $element) {
    $innerHTML = ""; 
    $children  = $element->childNodes;
    
    foreach ($children as $child) {
        $innerHTML .= $element->ownerDocument->saveHTML($child);
    }
    
    return $innerHTML; 
}