<?php

/**
 * Implements hook_init
 */
function webpage_from_hal_init() {
}

/**
 * Implements hook_filter_info
 */
function webpage_from_hal_filter_info() {
    return array(
        'webpage_from_hal' => array(
            'title' => t('Include html content from hal url'),
            'description' => t('Active this filter to allow a user adding a special balise to build a list of publications from HAL'),
            'settings callback' => '_filter_hal_settings',
            'process callback' => '_filter_hal',
        ),
    );
}

/**
 * Implements preprocess_node
 */
function webpage_from_hal_preprocess_node($variables) {
    $nodeId = $variables['nid'];
    drupal_add_css(variable_get(sprintf("node-%s.webpage_from_hal.css", $nodeId)), array('type' => 'external'));
}

function _filter_hal($text, $filter) {
    $nodeId = arg(1);
    $text = html_entity_decode($text);

    if (!preg_match('/\{\{\s*type\="webpage_from_hal"([^\}]+)\}\}/', $text, $matches)) {
        watchdog('webpage_from_hal', "No tag match", array(), WATCHDOG_DEBUG);
        return $text;
    }

    if (!preg_match("#url=\"([^\"]+)\"#", strip_tags($matches[1]), $uris)) {
        watchdog('webpage_from_hal', "Tag found but syntax error with url", array(), WATCHDOG_ERROR);
        return $text;
    }

    $infos = parse_url($uris[1]);
    $ip = gethostbyname($infos['host']);

    if ($ip != '193.48.96.10') {
        watchdog('webpage_from_hal', "Url invalid", array(), WATCHDOG_ERROR);
        
        return $text;
    }

    if (!preg_match("/css\=\.\.\/([^&]+)&?/", $uris[1], $css)) {
        watchdog('webpage_from_hal', "Fail getting css style from url", array(), WATCHDOG_DEBUG);
        variable_del(sprintf("node-%s.webpage_from_hal.css", $nodeId));
    } else {
        $cssUri = sprintf("http://hal.univ-grenoble-alpes.fr/%s", $css[1]);
        variable_set(sprintf("node-%s.webpage_from_hal.css", $nodeId), $cssUri);
    }

    watchdog('webpage_from_hal', sprintf("drupal_http_request(%s)", $uris[1]), array(), WATCHDOG_DEBUG);
    $content = drupal_http_request($uris[1]);
    watchdog('webpage_from_hal', "drupal_http_request: Done", array(), WATCHDOG_DEBUG);    

    $dom = new DomDocument('1.0', 'UTF-8');
    $dom->preserveWhiteSpace = false;

    $str = mb_convert_encoding($content->data, "HTML-ENTITIES");
    $dom->loadHTML($str);
    $xpath = new DOMXpath($dom);
    $entries = $xpath->query('//div[@id="res_script"]');

    if ($entries->length == 0) {
        watchdog('webpage_from_hal', 'Can\'t localized <div id="res_script">', array(), WATCHDOG_ERROR);

        return $text;
    }

    $res_script = $dom->saveXML($entries->item(0));


    $text = str_replace($matches[0], $res_script, $text);

    return $text;
}